services:
  web:
    build: .
    volumes:
      - ./:/app
    expose:
      - 8000
    ports:
      - 5678:5678
    environment:
      DATABASE_HOST: db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DEBUG: True
      DOCS: True
    networks:
      services_network:
        aliases:
          - web
    depends_on:
      - db

  db:
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      services_network:
        aliases:
          - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - services_network

volumes:
  postgres_data:

networks:
  services_network:
    driver: bridge